Add tastypie to MCPClient INSTALLED_APPS
This is needed because `archivematicaClient` calls `django.setup()`
which imports the `ApiAccess` model through the `helpers` module of
the dashboard producing this run time error:

```
RuntimeError: Model class tastypie.models.ApiAccess doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
```