Remove decoder output from PID declaration test
The message of the exception has changed in 3.13+ from:

json.decoder.JSONDecodeError: Expecting value: line 15 column 1 (char 336)

to:

json.decoder.JSONDecodeError: Illegal trailing comma before end of array: line 14 column 6 (char 334)

This updates the test to drop the decode error output from the
assertion and to look only for our own substring.