Fix integrity errors in reingest tests
This commit fixes some integrity errors in test_reingest_mets when loading
fixtures with invalid foreign keys. It is unclear why these errors are not
reproducible in the Docker environment.

FAILED tests/test_reingest_mets.py::TestAddingNewFiles::test_add_metadata_csv - django.db.utils.IntegrityError: The row in table 'Events_agents' with primary key '1' has an invalid foreign key: Events_agents.agent_id contains a value '1' that does not have a corresponding value in Agents.pk.
FAILED tests/test_reingest_mets.py::TestAddingNewFiles::test_no_new_files - django.db.utils.IntegrityError: The row in table 'Events_agents' with primary key '1' has an invalid foreign key: Events_agents.agent_id contains a value '1' that does not have a corresponding value in Agents.pk.
FAILED tests/test_reingest_mets.py::TestAddingNewFiles::test_new_metadata_file_in_subdir - django.db.utils.IntegrityError: The row in table 'Events_agents' with primary key '1' has an invalid foreign key: Events_agents.agent_id contains a value '1' that does not have a corresponding value in Agents.pk.
FAILED tests/test_reingest_mets.py::TestAddingNewFiles::test_new_preservation_file - django.db.utils.IntegrityError: The row in table 'Events_agents' with primary key '1' has an invalid foreign key: Events_agents.agent_id contains a value '1' that does not have a corresponding value in Agents.pk.
FAILED tests/test_reingest_mets.py::TestUpdateObject::test_update_file_id - django.db.utils.IntegrityError: The row in table 'Events_agents' with primary key '2' has an invalid foreign key: Events_agents.agent_id contains a value '3' that does not have a corresponding value in Agents.pk.
FAILED tests/test_reingest_mets.py::TestUpdateObject::test_update_all - django.db.utils.IntegrityError: The row in table 'Events_agents' with primary key '2' has an invalid foreign key: Events_agents.agent_id contains a value '3' that does not have a corresponding value in Agents.pk.
FAILED tests/test_reingest_mets.py::TestUpdateObject::test_update_checksum_type - django.db.utils.IntegrityError: The row in table 'Events_agents' with primary key '2' has an invalid foreign key: Events_agents.agent_id contains a value '3' that does not have a corresponding value in Agents.pk.
FAILED tests/test_reingest_mets.py::TestUpdateObject::test_update_preservation_derivative - django.db.utils.IntegrityError: The row in table 'Events_agents' with primary key '2' has an invalid foreign key: Events_agents.agent_id contains a value '3' that does not have a corresponding value in Agents.pk.
FAILED tests/test_reingest_mets.py::TestUpdateObject::test_object_not_updated - django.db.utils.IntegrityError: The row in table 'Events_agents' with primary key '2' has an invalid foreign key: Events_agents.agent_id contains a value '3' that does not have a corresponding value in Agents.pk.
FAILED tests/test_reingest_mets.py::TestUpdateObject::test_update_characterization - django.db.utils.IntegrityError: The row in table 'Events_agents' with primary key '2' has an invalid foreign key: Events_agents.agent_id contains a value '3' that does not have a corresponding value in Agents.pk.
FAILED tests/test_reingest_mets.py::TestUpdateObject::test__update_premis_object - django.db.utils.IntegrityError: The row in table 'Events_agents' with primary key '2' has an invalid foreign key: Events_agents.agent_id contains a value '3' that does not have a corresponding value in Agents.pk.
FAILED tests/test_reingest_mets.py::TestDeleteFiles::test_delete_file - django.db.utils.IntegrityError: The row in table 'Events_agents' with primary key '2' has an invalid foreign key: Events_agents.agent_id contains a value '3' that does not have a corresponding value in Agents.pk.