Update test to use a non UTC time zone
This test case represents a time zone and file modification time
combination that makes the job to fail in Archivematica 1.15.x.

In this commit the test fails because the expected time is now time
zone aware but the job has not been updated to use the current time
zone yet.

```console
FAILED test_store_file_modification.py::TestStoreFileModification::test_store_file_modification_dates - AssertionError: assert '2003-04-06 07:59:30+00:00' == '2003-04-06 02:59:30+00:00'

  - 2003-04-06 02:59:30+00:00
  ?             ^
  + 2003-04-06 07:59:30+00:00
  ?             ^
```